docs(install): rework NeoVim instructions
ngalaiko/tree-sitter-go-template pull request #20
Opened 2024-07-06 16:28 UTC by qvalentin

The parser and the queries are now added to the nvim-treesitter repo

2024-07-26 18:44 UTC, kmoschcau requested changes

2024-07-26 18:44 UTC, kmoschcau commented on README.md
> +Some people have been found to keep the repo going, so if you have ideas for improvements feel free to open issues or pull requests.
```suggestion
The original author stopped using helm (which he mostly wrote this package for) on a daily basis, so he didn't really keep up with the development of tree sitter, and nvim-tree-sitter.
Some people have been found to keep the repo going, so if you have ideas for improvements feel free to open issues or pull requests.
```

2024-07-26 18:44 UTC, kmoschcau commented on README.md
> +    -   for [helm][] the [vim-helm] plugin is recommended
I don't think recommending this plugin is a good idea. Users would only use it for file type detection, since highlighting is done by tree-sitter.

2024-07-26 18:44 UTC, kmoschcau commented on README.md
> +        })
```suggestion
        vim.filetype.add({
          extension = {
            gotmpl = 'gotmpl',
          },
          pattern = {
            [".*/templates/.*%.tpl"] = "helm",
            [".*/templates/.*%.yaml"] = "helm",
            ["helmfile.*%.yaml"] = "helm",
          },
        })
```

2024-08-04 15:06 UTC, qvalentin commented
Thanks @kmoschcau

2024-08-10 14:19 UTC, baptman21 approved these changes

2024-08-25 15:20 UTC, merged